//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AGROMET.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AGROMET.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Advisory.
        /// </summary>
        public static string AddAdvisory {
            get {
                return ResourceManager.GetString("AddAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Advisory Category.
        /// </summary>
        public static string AddAdvisoryCategory {
            get {
                return ResourceManager.GetString("AddAdvisoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Crop.
        /// </summary>
        public static string AddCrop {
            get {
                return ResourceManager.GetString("AddCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Notification.
        /// </summary>
        public static string AddNotification {
            get {
                return ResourceManager.GetString("AddNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisories.
        /// </summary>
        public static string Advisories {
            get {
                return ResourceManager.GetString("Advisories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory.
        /// </summary>
        public static string Advisory {
            get {
                return ResourceManager.GetString("Advisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory Category.
        /// </summary>
        public static string AdvisoryCategory {
            get {
                return ResourceManager.GetString("AdvisoryCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AdvisoryClose {
            get {
                return ResourceManager.GetString("AdvisoryClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory For.
        /// </summary>
        public static string AdvisoryFor {
            get {
                return ResourceManager.GetString("AdvisoryFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory List.
        /// </summary>
        public static string AdvisoryList {
            get {
                return ResourceManager.GetString("AdvisoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory Type.
        /// </summary>
        public static string AdvisoryType {
            get {
                return ResourceManager.GetString("AdvisoryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agro Advisory Details.
        /// </summary>
        public static string AgroAdvisoryDetails {
            get {
                return ResourceManager.GetString("AgroAdvisoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGROMET.
        /// </summary>
        public static string AGROMET {
            get {
                return ResourceManager.GetString("AGROMET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AGROMET Web Application.
        /// </summary>
        public static string AGROMETWebApplication {
            get {
                return ResourceManager.GetString("AGROMETWebApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agronomy.
        /// </summary>
        public static string Agronomy {
            get {
                return ResourceManager.GetString("Agronomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts.
        /// </summary>
        public static string Alerts {
            get {
                return ResourceManager.GetString("Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerts Type.
        /// </summary>
        public static string AlertsType {
            get {
                return ResourceManager.GetString("AlertsType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio.
        /// </summary>
        public static string Audio {
            get {
                return ResourceManager.GetString("Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Block.
        /// </summary>
        public static string Block {
            get {
                return ResourceManager.GetString("Block", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        public static string Blocks {
            get {
                return ResourceManager.GetString("Blocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Text.
        /// </summary>
        public static string BriefText {
            get {
                return ResourceManager.GetString("BriefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulletin No..
        /// </summary>
        public static string BulletinNo {
            get {
                return ResourceManager.GetString("BulletinNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title Characters Count.
        /// </summary>
        public static string CharactersCount {
            get {
                return ResourceManager.GetString("CharactersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear All.
        /// </summary>
        public static string ClearAll {
            get {
                return ResourceManager.GetString("ClearAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string CompleteMessage {
            get {
                return ResourceManager.GetString("CompleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Alert.
        /// </summary>
        public static string CreateAlert {
            get {
                return ResourceManager.GetString("CreateAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop.
        /// </summary>
        public static string Crop {
            get {
                return ResourceManager.GetString("Crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Advisory.
        /// </summary>
        public static string CropAdvisory {
            get {
                return ResourceManager.GetString("CropAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Advisory Audio.
        /// </summary>
        public static string CropAdvisoryAudio {
            get {
                return ResourceManager.GetString("CropAdvisoryAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Advisory Images.
        /// </summary>
        public static string CropAdvisoryImages {
            get {
                return ResourceManager.GetString("CropAdvisoryImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop List.
        /// </summary>
        public static string CropList {
            get {
                return ResourceManager.GetString("CropList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crops.
        /// </summary>
        public static string Crops {
            get {
                return ResourceManager.GetString("Crops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DASHBOARD.
        /// </summary>
        public static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dept.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designation.
        /// </summary>
        public static string Designation {
            get {
                return ResourceManager.GetString("Designation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District.
        /// </summary>
        public static string District {
            get {
                return ResourceManager.GetString("District", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Districts.
        /// </summary>
        public static string Districts {
            get {
                return ResourceManager.GetString("Districts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmailID.
        /// </summary>
        public static string EmailID {
            get {
                return ResourceManager.GetString("EmailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Agro Advisory Details.
        /// </summary>
        public static string EnterAgroAdvisoryDetails {
            get {
                return ResourceManager.GetString("EnterAgroAdvisoryDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter SMS Text.
        /// </summary>
        public static string EnterBriefText {
            get {
                return ResourceManager.GetString("EnterBriefText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Advisory.
        /// </summary>
        public static string EnterMessage {
            get {
                return ResourceManager.GetString("EnterMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter 10 digit mobile number.
        /// </summary>
        public static string EnterMobile {
            get {
                return ResourceManager.GetString("EnterMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Option 1 Title.
        /// </summary>
        public static string EnterOptionOneTitle {
            get {
                return ResourceManager.GetString("EnterOptionOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entet Option 2 Title.
        /// </summary>
        public static string EnterOptionTwoTitle {
            get {
                return ResourceManager.GetString("EnterOptionTwoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        public static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Question.
        /// </summary>
        public static string EnterQuestion {
            get {
                return ResourceManager.GetString("EnterQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Advisory.
        /// </summary>
        public static string EnterRecommendations {
            get {
                return ResourceManager.GetString("EnterRecommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter search term.
        /// </summary>
        public static string Entersearchterm {
            get {
                return ResourceManager.GetString("Entersearchterm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter SMS Text.
        /// </summary>
        public static string EnterSMSText {
            get {
                return ResourceManager.GetString("EnterSMSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Enter Title.
        /// </summary>
        public static string EnterTitle {
            get {
                return ResourceManager.GetString("EnterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Weather Condition / Description.
        /// </summary>
        public static string EnterWeatherCondition {
            get {
                return ResourceManager.GetString("EnterWeatherCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer Details.
        /// </summary>
        public static string FarmerDetails {
            get {
                return ResourceManager.GetString("FarmerDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FarmerName {
            get {
                return ResourceManager.GetString("FarmerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farmer Name.
        /// </summary>
        public static string FarmerNames {
            get {
                return ResourceManager.GetString("FarmerNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string FarmerPhone {
            get {
                return ResourceManager.GetString("FarmerPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string FeMale {
            get {
                return ResourceManager.GetString("FeMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget PIN.
        /// </summary>
        public static string ForgetPIN {
            get {
                return ResourceManager.GetString("ForgetPIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get SMS.
        /// </summary>
        public static string GetSMS {
            get {
                return ResourceManager.GetString("GetSMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go Back.
        /// </summary>
        public static string GoBack {
            get {
                return ResourceManager.GetString("GoBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        public static string Institution {
            get {
                return ResourceManager.GetString("Institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGOUT.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Application.
        /// </summary>
        public static string MobileApplication {
            get {
                return ResourceManager.GetString("MobileApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found!.
        /// </summary>
        public static string Nodatafound {
            get {
                return ResourceManager.GetString("Nodatafound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select either mobile or sms notification checkbox!.
        /// </summary>
        public static string Notificationerr {
            get {
                return ResourceManager.GetString("Notificationerr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Method.
        /// </summary>
        public static string NotificationMethod {
            get {
                return ResourceManager.GetString("NotificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your browser does not support the audio element..
        /// </summary>
        public static string NotSupport {
            get {
                return ResourceManager.GetString("NotSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 1 Title.
        /// </summary>
        public static string OptionOneTitle {
            get {
                return ResourceManager.GetString("OptionOneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option 2 Title.
        /// </summary>
        public static string OptionTwoTitle {
            get {
                return ResourceManager.GetString("OptionTwoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PinCode.
        /// </summary>
        public static string PinCode {
            get {
                return ResourceManager.GetString("PinCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select.
        /// </summary>
        public static string Pleaseselect {
            get {
                return ResourceManager.GetString("Pleaseselect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publish.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        public static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisory.
        /// </summary>
        public static string Recommendations {
            get {
                return ResourceManager.GetString("Recommendations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientist Name.
        /// </summary>
        public static string ScientistName {
            get {
                return ResourceManager.GetString("ScientistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Advisory.
        /// </summary>
        public static string SearchAdvisory {
            get {
                return ResourceManager.GetString("SearchAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Users.
        /// </summary>
        public static string SearchUsers {
            get {
                return ResourceManager.GetString("SearchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --Select--.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string Selectall {
            get {
                return ResourceManager.GetString("Selectall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string SelectCategory {
            get {
                return ResourceManager.GetString("SelectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Crop.
        /// </summary>
        public static string SelectCrop {
            get {
                return ResourceManager.GetString("SelectCrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Date.
        /// </summary>
        public static string SelectDate {
            get {
                return ResourceManager.GetString("SelectDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Notification.
        /// </summary>
        public static string SendNotification {
            get {
                return ResourceManager.GetString("SendNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Area.
        /// </summary>
        public static string ServiceArea {
            get {
                return ResourceManager.GetString("ServiceArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Alert.
        /// </summary>
        public static string SmsAlert {
            get {
                return ResourceManager.GetString("SmsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Text.
        /// </summary>
        public static string SMSText {
            get {
                return ResourceManager.GetString("SMSText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surveys.
        /// </summary>
        public static string Surveys {
            get {
                return ResourceManager.GetString("Surveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Advisory.
        /// </summary>
        public static string TotalAdvisory {
            get {
                return ResourceManager.GetString("TotalAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transalate.
        /// </summary>
        public static string Transalate {
            get {
                return ResourceManager.GetString("Transalate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transalation Required.
        /// </summary>
        public static string Transalationrequired {
            get {
                return ResourceManager.GetString("Transalationrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Audio.
        /// </summary>
        public static string UploadAudioFile {
            get {
                return ResourceManager.GetString("UploadAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Image.
        /// </summary>
        public static string UploadImageFiles {
            get {
                return ResourceManager.GetString("UploadImageFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientist Profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scientists.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEATHER.
        /// </summary>
        public static string Weather {
            get {
                return ResourceManager.GetString("Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weather Condition / Description.
        /// </summary>
        public static string WeatherCondition {
            get {
                return ResourceManager.GetString("WeatherCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Tube Link.
        /// </summary>
        public static string YouTubeLink {
            get {
                return ResourceManager.GetString("YouTubeLink", resourceCulture);
            }
        }
    }
}
